metaplane_dbt:
    outputs:
        prod:                     # specify the prod connection
            type: snowflake
            threads: 10
            account: {"env": "SNOWFLAKE_ACCOUNT"}     # the url prefix for your snowflake connection,
                                  # i.e. evilcorp.snowflakecomputing.com
            user: {"env": "SNOWFLAKE_USER"}
            password:  {"env": "SNOWFLAKE_PW"}
            role: transformer        # optional, the snowflake role you want to use
                                  # when connecting
            database: prod_analytics
            warehouse: transforming
            schema: analytics     # use the prod schema instead