metaplane_dbt:
    outputs:
        default:                     # specify the prod connection
            type: snowflake
            threads: 10
            account: ${SNOWFLAKE_ACCOUNT}     # the url prefix for your snowflake connection,
                                  # i.e. evilcorp.snowflakecomputing.com
            user: ${SNOWFLAKE_USER}
            password:  ${SNOWFLAKE_PW}
            role: transformer        # optional, the snowflake role you want to use
                                  # when connecting
            database: prod_analytics
            warehouse: transforming
            schema: analytics     # use the prod schema instead
        target: default