metaplane_dbt:
    outputs:
        default:                     # specify the prod connection
            type: snowflake
            threads: 10
            account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"    # the url prefix for your snowflake connection,
                                  # i.e. evilcorp.snowflakecomputing.com
            user: "{{ env_var('SNOWFLAKE_USER') }}"
            password:  "{{ env_var('SNOWFLAKE_PW') }}"
            role: transformer        # optional, the snowflake role you want to use
                                  # when connecting
            database: prod_analytics
            warehouse: transforming
            schema: analytics     # use the prod schema instead
        target: default